VehicleAdvertisementSystem/Controllers/AdvertisementsController.cs
namespace VehicleAdvertisementSystem.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    using Models.Advertisements;
    using Data.Models;
    using VehicleAdvertisementSystem.Data;

    public class AdvertisementsController : Controller
    {
        private readonly AdvertisementSystemDbContext data;

        public AdvertisementsController(AdvertisementSystemDbContext data)
            => this.data = data;

        public IActionResult Add() => View(new AddAdvertisementFormModel
        {
            VehicleTypes = this.GetVehicleTypes(),
            ConditionStatuses = this.GetConditionStatuses(),
            TransmissionTypes = this.GetTransmissionTypes(),
            FuelTypes = this.GetFuelTypes(),
            Eurostandards = this.GetEurostandards(),
        });

        public IActionResult All() 
        { 
            var advertisments = this.data
                .Advertisements
                .OrderByDescending(a => a.Id)
                .Select( a => new AdvertismentListingViewModel
                {
                    Id = a.Id,
                    Make = a.Make,
                    Model = a.Model,
                    ImageUrl = a.ImageUrl,
                    Price = a.Price
                })
                .ToList();

            return View(advertisments);
        }

        [HttpPost]
        public IActionResult Add(AddAdvertisementFormModel advertisement)
        {
            if (!this.data.VehicleTypes.Any(t => t.Id == advertisement.VehicleTypeId))
            {
                this.ModelState.AddModelError(nameof(advertisement.VehicleTypeId), "Vehicle type does not exist.");
            }

            if (!this.data.ConditionStatuses.Any(c => c.Id == advertisement.ConditionStatusId))
            {
                this.ModelState.AddModelError(nameof(advertisement.ConditionStatusId), "Condition status does not exist.");
            }

            if (!this.data.Transmissions.Any(t => t.Id == advertisement.TransmissionId))
            {
                this.ModelState.AddModelError(nameof(advertisement.TransmissionId), "Transmission type does not exist.");
            }

            if (!this.data.FuelTypes.Any(t => t.Id == advertisement.FuelId))
            {
                this.ModelState.AddModelError(nameof(advertisement.FuelId), "Fuel type does not exist.");
            }

            if (!this.data.Eurostandards.Any(t => t.Id == advertisement.EurostandardId))
            {
                this.ModelState.AddModelError(nameof(advertisement.EurostandardId), "Eurostanderd does not exist.");
            }

            if (!ModelState.IsValid)
            {
                advertisement.VehicleTypes = this.GetVehicleTypes();
                advertisement.ConditionStatuses = this.GetConditionStatuses();
                advertisement.TransmissionTypes = this.GetTransmissionTypes();
                advertisement.FuelTypes = this.GetFuelTypes();
                advertisement.Eurostandards = this.GetEurostandards();
                return View(advertisement);
            }

            var advertisementData = new Advertisement
            {
                VehicleTypeId = advertisement.VehicleTypeId,
                ConditionStatusId = advertisement.ConditionStatusId,
                Make = advertisement.Make,
                Model = advertisement.Model,
                ImageUrl = advertisement.ImageUrl,
                Mileage = advertisement.Mileage,
                Price = advertisement.Price,
                TransmissionId = advertisement.TransmissionId,
                FuelId = advertisement.FuelId,
                Power = advertisement.Power,
                Year = advertisement.Year,
                Month = advertisement.Month,
                NumberOfDoors = advertisement.NumberOfDoors,
                NumberOfSeats = advertisement.NumberOfSeats,
                Color = advertisement.Color,
                EurostandardId = advertisement.EurostandardId,
                NewImportation = advertisement.NewImportation,
                DateOfPublication = DateTime.UtcNow,
                Description = advertisement.Description,           
            };

            this.data.Advertisements.Add(advertisementData);
            this.data.SaveChanges();

            return RedirectToAction(nameof(All));
        }

        private IEnumerable<VehicleTypeViewModel> GetVehicleTypes()
            => this.data
            .VehicleTypes
            .Select(t => new VehicleTypeViewModel
            {
                Id = t.Id,
                Name = t.Name,
            })
            .ToList();

        private IEnumerable<ConditionStatusViewModel> GetConditionStatuses()
            => this.data
            .ConditionStatuses
            .Select(x => new ConditionStatusViewModel
            {
                Id = x.Id,
                Name = x.Name,
            })
            .ToList();

        private IEnumerable<TransmissionTypeViewModel> GetTransmissionTypes()
            => this.data
            .Transmissions
            .Select(x => new TransmissionTypeViewModel
            {
                Id = x.Id,
                Type = x.Type,
            })
            .ToList();

        private IEnumerable<FuelViewModel> GetFuelTypes()
            => this.data
            .FuelTypes
            .Select(x => new FuelViewModel
            {
                Id = x.Id,
                Name = x.Name
            })
            .ToList();

        private IEnumerable<EurostandardViewModel> GetEurostandards()
            => this.data
            .Eurostandards
            .Select(x => new EurostandardViewModel
            {
                Id = x.Id,
                Name = x.Name
            })
            .ToList();
    }
}

VehicleAdvertisementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Car Advertisements </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VehicleAdvertisementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Car Advertisments</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Advertisements" asp-action="Add">Add Advertisement</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Advertisements" asp-action="All">All Advertisements</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - VehicleAdvertisementSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>